# Use the docker infrastructure.
sudo: false

# for cabal
language: haskell
ghc: 7.8

cache:
  directories:
    - $HOME/.stack

notifications:
  email:
    on_success: change
    on_failure: change

env:
  matrix:
    - STACK_YAML=stack-2.14.yaml
    - STACK_YAML=stack-2.18.yaml
    - STACK_YAML=stack-2.20.yaml

install:
 - travis_retry wget https://github.com/commercialhaskell/stack/releases/download/v0.1.2.0/stack-0.1.2.0-x86_64-linux.gz
 - gunzip stack-0.1.2.0-x86_64-linux.gz
 - mv stack-0.1.2.0-x86_64-linux stack
 - chmod +x stack

# Here starts the actual work to be performed for the package under test; any
# command which exits with a non-zero exit code causes the build to fail.
script:
 - cabal check
 - cabal sdist
 - export SRC=$(cabal info . | awk '{print $2;exit}')
 - tar -xzf "dist/$SRC.tar.gz"
 - cd "$SRC"
 - cp ../$STACK_YAML .
 - cp ../stack .
 - travis_retry ./stack setup
 - travis_retry ./stack install --only-snapshot -j4 --verbosity info
 - ./stack build
 - ./stack test
 - ./stack haddock --no-haddock-deps
 - export DIST_DIR=$(./stack path --dist-dir --stack-yaml $STACK_YAML)
 - echo $DIST_DIR
